// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createData = `-- name: CreateData :one
INSERT INTO data (project, id, code_block, file_path, line, description) VALUES ($1, $2, $3, $4, $5, $6) RETURNING project, id, code_block, file_path, line, description
`

type CreateDataParams struct {
	Project     string
	ID          int64
	CodeBlock   pgtype.Text
	FilePath    pgtype.Text
	Line        pgtype.Int4
	Description pgtype.Text
}

func (q *Queries) CreateData(ctx context.Context, arg CreateDataParams) (Datum, error) {
	row := q.db.QueryRow(ctx, createData,
		arg.Project,
		arg.ID,
		arg.CodeBlock,
		arg.FilePath,
		arg.Line,
		arg.Description,
	)
	var i Datum
	err := row.Scan(
		&i.Project,
		&i.ID,
		&i.CodeBlock,
		&i.FilePath,
		&i.Line,
		&i.Description,
	)
	return i, err
}

const deleteData = `-- name: DeleteData :one
DELETE FROM data WHERE project = $1 AND id = $2 RETURNING project, id, code_block, file_path, line, description
`

type DeleteDataParams struct {
	Project string
	ID      int64
}

func (q *Queries) DeleteData(ctx context.Context, arg DeleteDataParams) (Datum, error) {
	row := q.db.QueryRow(ctx, deleteData, arg.Project, arg.ID)
	var i Datum
	err := row.Scan(
		&i.Project,
		&i.ID,
		&i.CodeBlock,
		&i.FilePath,
		&i.Line,
		&i.Description,
	)
	return i, err
}

const deleteDataList = `-- name: DeleteDataList :many
DELETE FROM data WHERE project = $1 AND id = ANY($2::int[]) RETURNING project, id, code_block, file_path, line, description
`

type DeleteDataListParams struct {
	Project string
	Column2 []int32
}

func (q *Queries) DeleteDataList(ctx context.Context, arg DeleteDataListParams) ([]Datum, error) {
	rows, err := q.db.Query(ctx, deleteDataList, arg.Project, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.Project,
			&i.ID,
			&i.CodeBlock,
			&i.FilePath,
			&i.Line,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProjectData = `-- name: DeleteProjectData :many
DELETE FROM data WHERE project = $1 RETURNING project, id, code_block, file_path, line, description
`

func (q *Queries) DeleteProjectData(ctx context.Context, project string) ([]Datum, error) {
	rows, err := q.db.Query(ctx, deleteProjectData, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.Project,
			&i.ID,
			&i.CodeBlock,
			&i.FilePath,
			&i.Line,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getData = `-- name: GetData :one
SELECT project, id, code_block, file_path, line, description FROM data WHERE project = $1 AND id = $2
`

type GetDataParams struct {
	Project string
	ID      int64
}

func (q *Queries) GetData(ctx context.Context, arg GetDataParams) (Datum, error) {
	row := q.db.QueryRow(ctx, getData, arg.Project, arg.ID)
	var i Datum
	err := row.Scan(
		&i.Project,
		&i.ID,
		&i.CodeBlock,
		&i.FilePath,
		&i.Line,
		&i.Description,
	)
	return i, err
}

const getDataList = `-- name: GetDataList :many
SELECT project, id, code_block, file_path, line, description FROM data WHERE project = $1 AND id = ANY($2::int[])
`

type GetDataListParams struct {
	Project string
	Column2 []int32
}

func (q *Queries) GetDataList(ctx context.Context, arg GetDataListParams) ([]Datum, error) {
	rows, err := q.db.Query(ctx, getDataList, arg.Project, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datum
	for rows.Next() {
		var i Datum
		if err := rows.Scan(
			&i.Project,
			&i.ID,
			&i.CodeBlock,
			&i.FilePath,
			&i.Line,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateData = `-- name: UpdateData :one
UPDATE data SET code_block = $3, file_path = $4, line = $5, description = $6 WHERE project = $1 AND id = $2 RETURNING project, id, code_block, file_path, line, description
`

type UpdateDataParams struct {
	Project     string
	ID          int64
	CodeBlock   pgtype.Text
	FilePath    pgtype.Text
	Line        pgtype.Int4
	Description pgtype.Text
}

func (q *Queries) UpdateData(ctx context.Context, arg UpdateDataParams) (Datum, error) {
	row := q.db.QueryRow(ctx, updateData,
		arg.Project,
		arg.ID,
		arg.CodeBlock,
		arg.FilePath,
		arg.Line,
		arg.Description,
	)
	var i Datum
	err := row.Scan(
		&i.Project,
		&i.ID,
		&i.CodeBlock,
		&i.FilePath,
		&i.Line,
		&i.Description,
	)
	return i, err
}
